### ISSUE TITLE
relaxe AssetRole check

### ISSUE THREAD

**Issue by vincentsarago** [arturo-ai/stac-pydantic#38]
The enum should be used as example, not as strict values!
https://github.com/arturo-ai/stac-pydantic/blob/e54d113725394f42b2f17b748a27d1d5b04b8713/stac_pydantic/shared.py#L90-L98

the specification says 
> the roles field can be given any value

ref: https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-role-types

**Comment by geospatial-jeff** [comment]
Agreed, similar change as https://github.com/arturo-ai/stac-pydantic/pull/35
