### ISSUE TITLE
Use 'id' on LandingPage

### ISSUE THREAD

**Issue by lossyrob** [arturo-ai/stac-pydantic#42]
According to [the api spec](https://github.com/radiantearth/stac-api-spec/blob/master/api-spec.md#ogc-api---features-endpoints), the root landing page should be a valid Catalog. Currently the `LandingPage` model does not have an `id` attribute. This causes the "root" link for objects returned from `arturo-stac-api` to point to an invalid catalog, and so when links are crawled e.g. via PySTAC an exception is thrown.

If you agree this is an issue, I'll make a PR.

**Comment by geospatial-jeff** [comment]
definitely agree!  nice catch!
